# Generated by Django 5.1.6 on 2025-06-05 18:33

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=colorfield.fields.ColorField(default='#D6D6D6', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='totalTime',
            field=models.TimeField(null=True),
        ),
    ]
